name: Reusable Workflow

on:
  repository_dispatch:
    types: [trigger-reusable-workflow]

jobs:
  process-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Message received:" ${{ github.event.client_payload.message }}
