name: Reusable Workflow

on:
  repository_dispatch:
    types: [trigger-reusable-workflow]

jobs:
  downloaded-zip:
    runs-on: ubuntu-latest
    outputs:
      # Define an output variable to store the path of the downloaded file
      id: downloaded_file
      value: /tmp/mediplus-lite.zip
    steps:
      - name: Print Message
        run: |
          echo "Message received: ${{ github.event.client_payload.inputs.message }}"
          echo "Message received: ${{ github.event.client_payload.inputs.json_file_path }}"
          json_file_path=doc-publisher-workflow/${{ github.event.client_payload.inputs.json_file_path }}
          echo "Processing JSON file at $json_file_path"
          
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Install requests
        run: python -m pip install requests
      - name: Read and print JSON values
        run: python .github/scripts/read_json.py https://gbfs.citibikenyc.com/gbfs/en/station_information.json
      - name: Run Python script
        run: python .github/scripts/download_zip.py
      - name: List downloaded files
        run: |
          # List the contents of the temporary location
          ls -la /tmp/
      - name: Upload downloaded file as artifact
        uses: actions/upload-artifact@v2
        with:
           name: downloaded-zip
           path: ${{ needs.download-zip.outputs.downloaded_file }}
