name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        required: true

jobs:
  process-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "Message received: ${{ github.event.inputs.message }}"
